#!/usr/bin/env bash
set -euo pipefail

# Harness CI Check Script
# Generated by: harness ci init --platform generic

if ! command -v harness &> /dev/null; then
  echo "Installing @harness-engineering/cli..."
  npm install -g @harness-engineering/cli
fi

echo "Running harness checks..."
harness ci check --json
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  echo "All harness checks passed."
elif [ $EXIT_CODE -eq 1 ]; then
  echo "Harness checks failed. See report above."
else
  echo "Harness internal error."
fi

exit $EXIT_CODE
